%% legend_actino
% specification of a legend for Actinopterygii

%
function legend = legend_actino
% created at 2017/04/20 by Bas Kooijman

  %% Syntax
  % legend = <legend_actino.m *legend_actino*>

  %% Description
  % Specifies a legend for Actinopterygii
  %
  % Output
  %
  % * legend: (8,2) cell matrix with (marker, taxon)-pairs

  % type, size, linewidth, edge color and face color of a marker, taxon
  legend = {...
    {'o', 8, 3, [1 0 0], [1 0 0]}, 'Perciformes'; ...
    {'o', 8, 3, [1 0 0], [0 0 1]}, 'Eupercaria'; ...
    {'o', 8, 3, [1 0 0], [0 0 0]}, 'Percomorphaceae'; ...
    {'o', 8, 3, [1 0 1], [1 0 1]}, 'Acanthomorphata'; ...
    {'o', 8, 3, [1 0 1], [0 0 1]}, 'Myctophata'; ...
    {'o', 8, 3, [1 0 1], [0 0 0]}, 'Aulopa'; ...
    {'o', 8, 3, [0 0 1], [0 0 1]}, 'Euteleosteomorpha'; ....
    {'o', 8, 3, [0 0 1], [0 0 0]}, 'Otomorpha'; ....
    {'o', 8, 3, [0 0 0], [1 0 0]}, 'Osteoglossocephalai'; ....
    {'o', 8, 3, [0 0 0], [1 0 1]}, 'Holostei'; ....
    {'o', 8, 3, [0 0 0], [0 0 1]}, 'Cladistii'; ....
    {'.', 8, 3, [0 0 0], [0 0 0]}, 'Actinopterygii'; ....
  };
end
