//
// Copyright (c) 2006 by Conor O''Mahony.
// For enquiries, please email GubuSoft@GubuSoft.com
// Please keep all copyright notices below.
// Original author of TreeView script is Marcelino Martins.
// This document includes the TreeView script.
// The TreeView script can be found at http://www.TreeView.net.
// The script is Copyright (c) 2006 by Conor O''Mahony.
//
// You can find general instructions for this file at www.treeview.net.
//

USETEXTLINKS = 1
STARTALLOPEN = 0
USEFRAMES = 0
USEICONS = 0
WRAPTEXT = 1
PRESERVESTATE = 1
HIGHLIGHT = 1

foldersTree = gFld("<b>Mammalia</b>", "treeview_taxa.html")
L2 = insFld(foldersTree, gFld("Prototheria", "treeview_taxa.html?pic=%22Prototheria%2Ejpg%22"))
L3 = insFld(L2, gFld("Monotremata", "treeview_taxa.html?pic=%22Monotremata%2Ejpg%22"))
L4 = insFld(L3, gFld("Ornithorhynchidae", "treeview_taxa.html?pic=%22Ornithorhynchidae%2Ejpg%22"))
L5 = insFld(L4, gFld("Ornithorhynchus", "treeview_taxa.html?pic=%22Ornithorhynchus%2Ejpg%22"))
insDoc(L5, gLnk("S", "Ornithorhynchus_anatinus", "http://www.bio.vu.nl/thb/deb/deblab/add_my_pet/entries_web/Ornithorhynchus_anatinus_res.html"))
L4 = insFld(L3, gFld("Tachyglossidae", "treeview_taxa.html?pic=%22Tachyglossidae%2Ejpg%22"))
L5 = insFld(L4, gFld("Tachyglossus", "treeview_taxa.html?pic=%22Tachyglossus%2Ejpg%22"))
insDoc(L5, gLnk("S", "Tachyglossus_aculeatus", "http://www.bio.vu.nl/thb/deb/deblab/add_my_pet/entries_web/Tachyglossus_aculeatus_res.html"))
L2 = insFld(foldersTree, gFld("Theriiformes", "treeview_taxa.html?pic=%22Theriiformes%2Ejpg%22"))
L3 = insFld(L2, gFld("Marsupialia", "treeview_taxa.html?pic=%22Marsupialia%2Ejpg%22"))
L4 = insFld(L3, gFld("Didelphimorphia", "treeview_taxa.html?pic=%22Didelphimorphia%2Ejpg%22"))
L5 = insFld(L4, gFld("Caluromyidae", "treeview_taxa.html?pic=%22Caluromyidae%2Ejpg%22"))
L6 = insFld(L5, gFld("Caluromys", "treeview_taxa.html?pic=%22Caluromys%2Ejpg%22"))
insDoc(L6, gLnk("S", "Caluromys_philander", "http://www.bio.vu.nl/thb/deb/deblab/add_my_pet/entries_web/Caluromys_philander_res.html"))
L5 = insFld(L4, gFld("Didelphidae", "treeview_taxa.html?pic=%22Didelphidae%2Ejpg%22"))
L6 = insFld(L5, gFld("Didelphis", "treeview_taxa.html?pic=%22Didelphis%2Ejpg%22"))
insDoc(L6, gLnk("S", "Didelphis_virginiana", "http://www.bio.vu.nl/thb/deb/deblab/add_my_pet/entries_web/Didelphis_virginiana_res.html"))
L4 = insFld(L3, gFld("Dasyuromorphia", "treeview_taxa.html?pic=%22Dasyuromorphia%2Ejpg%22"))
L5 = insFld(L4, gFld("Dasyuridae", "treeview_taxa.html?pic=%22Dasyuridae%2Ejpg%22"))
L6 = insFld(L5, gFld("Sarcophilus", "treeview_taxa.html?pic=%22Sarcophilus%2Ejpg%22"))
insDoc(L6, gLnk("S", "Sarcophilus_harrisii", "http://www.bio.vu.nl/thb/deb/deblab/add_my_pet/entries_web/Sarcophilus_harrisii_res.html"))
L6 = insFld(L5, gFld("Dasyurus", "treeview_taxa.html?pic=%22Dasyurus%2Ejpg%22"))
insDoc(L6, gLnk("S", "Dasyurus_viverrinus", "http://www.bio.vu.nl/thb/deb/deblab/add_my_pet/entries_web/Dasyurus_viverrinus_res.html"))
L4 = insFld(L3, gFld("Peramelemorphia", "treeview_taxa.html?pic=%22Peramelemorphia%2Ejpg%22"))
L5 = insFld(L4, gFld("Peramelidae", "treeview_taxa.html?pic=%22Peramelidae%2Ejpg%22"))
L6 = insFld(L5, gFld("Perameles", "treeview_taxa.html?pic=%22Perameles%2Ejpg%22"))
insDoc(L6, gLnk("S", "Perameles_nasuta", "http://www.bio.vu.nl/thb/deb/deblab/add_my_pet/entries_web/Perameles_nasuta_res.html"))
L4 = insFld(L3, gFld("Diprotodontia", "treeview_taxa.html?pic=%22Diprotodontia%2Ejpg%22"))
L5 = insFld(L4, gFld("Phascolarctidae", "treeview_taxa.html?pic=%22Phascolarctidae%2Ejpg%22"))
L6 = insFld(L5, gFld("Phascolarctos", "treeview_taxa.html?pic=%22Phascolarctos%2Ejpg%22"))
insDoc(L6, gLnk("S", "Phascolarctos_cinereus", "http://www.bio.vu.nl/thb/deb/deblab/add_my_pet/entries_web/Phascolarctos_cinereus_res.html"))
L5 = insFld(L4, gFld("Tarsipedidae", "treeview_taxa.html?pic=%22Tarsipedidae%2Ejpg%22"))
L6 = insFld(L5, gFld("Tarsipes", "treeview_taxa.html?pic=%22Tarsipes%2Ejpg%22"))
insDoc(L6, gLnk("S", "Tarsipes_rostratus", "http://www.bio.vu.nl/thb/deb/deblab/add_my_pet/entries_web/Tarsipes_rostratus_res.html"))
L5 = insFld(L4, gFld("Macropodidae", "treeview_taxa.html?pic=%22Macropodidae%2Ejpg%22"))
L6 = insFld(L5, gFld("Lagostrophus", "treeview_taxa.html?pic=%22Lagostrophus%2Ejpg%22"))
insDoc(L6, gLnk("S", "Lagostrophus_fasciatus", "http://www.bio.vu.nl/thb/deb/deblab/add_my_pet/entries_web/Lagostrophus_fasciatus_res.html"))
L6 = insFld(L5, gFld("Lagorchestes", "treeview_taxa.html?pic=%22Lagorchestes%2Ejpg%22"))
insDoc(L6, gLnk("S", "Lagorchestes_conspicillatus", "http://www.bio.vu.nl/thb/deb/deblab/add_my_pet/entries_web/Lagorchestes_conspicillatus_res.html"))
insDoc(L6, gLnk("S", "Lagorchestes_hirsutus", "http://www.bio.vu.nl/thb/deb/deblab/add_my_pet/entries_web/Lagorchestes_hirsutus_res.html"))
L6 = insFld(L5, gFld("Macropus", "treeview_taxa.html?pic=%22Macropus%2Ejpg%22"))
insDoc(L6, gLnk("S", "Macropus_agilis", "http://www.bio.vu.nl/thb/deb/deblab/add_my_pet/entries_web/Macropus_agilis_res.html"))
insDoc(L6, gLnk("S", "Macropus_antilopinus", "http://www.bio.vu.nl/thb/deb/deblab/add_my_pet/entries_web/Macropus_antilopinus_res.html"))
insDoc(L6, gLnk("S", "Macropus_eugenii", "http://www.bio.vu.nl/thb/deb/deblab/add_my_pet/entries_web/Macropus_eugenii_res.html"))
insDoc(L6, gLnk("S", "Macropus_fuliginosus", "http://www.bio.vu.nl/thb/deb/deblab/add_my_pet/entries_web/Macropus_fuliginosus_res.html"))
insDoc(L6, gLnk("S", "Macropus_giganteus", "http://www.bio.vu.nl/thb/deb/deblab/add_my_pet/entries_web/Macropus_giganteus_res.html"))
insDoc(L6, gLnk("S", "Macropus_parma", "http://www.bio.vu.nl/thb/deb/deblab/add_my_pet/entries_web/Macropus_parma_res.html"))
insDoc(L6, gLnk("S", "Macropus_rufogriseus", "http://www.bio.vu.nl/thb/deb/deblab/add_my_pet/entries_web/Macropus_rufogriseus_res.html"))
insDoc(L6, gLnk("S", "Macropus_rufus", "http://www.bio.vu.nl/thb/deb/deblab/add_my_pet/entries_web/Macropus_rufus_res.html"))
L6 = insFld(L5, gFld("Onychogalea", "treeview_taxa.html?pic=%22Onychogalea%2Ejpg%22"))
insDoc(L6, gLnk("S", "Onychogalea_fraenata", "http://www.bio.vu.nl/thb/deb/deblab/add_my_pet/entries_web/Onychogalea_fraenata_res.html"))
L6 = insFld(L5, gFld("Petrogale", "treeview_taxa.html?pic=%22Petrogale%2Ejpg%22"))
insDoc(L6, gLnk("S", "Petrogale_xanthopus", "http://www.bio.vu.nl/thb/deb/deblab/add_my_pet/entries_web/Petrogale_xanthopus_res.html"))
L6 = insFld(L5, gFld("Setonix", "treeview_taxa.html?pic=%22Setonix%2Ejpg%22"))
insDoc(L6, gLnk("S", "Setonix_brachyurus", "http://www.bio.vu.nl/thb/deb/deblab/add_my_pet/entries_web/Setonix_brachyurus_res.html"))
L6 = insFld(L5, gFld("Wallabia", "treeview_taxa.html?pic=%22Wallabia%2Ejpg%22"))
insDoc(L6, gLnk("S", "Wallabia_bicolor", "http://www.bio.vu.nl/thb/deb/deblab/add_my_pet/entries_web/Wallabia_bicolor_res.html"))
L3 = insFld(L2, gFld("Placentalia", "treeview_taxa.html?pic=%22Placentalia%2Ejpg%22"))
L4 = insFld(L3, gFld("Xenarthra", "treeview_taxa.html?pic=%22Xenarthra%2Ejpg%22"))
L5 = insFld(L4, gFld("Pilosa", "treeview_taxa.html?pic=%22Pilosa%2Ejpg%22"))
L6 = insFld(L5, gFld("Myrmecophagidae", "treeview_taxa.html?pic=%22Myrmecophagidae%2Ejpg%22"))
L7 = insFld(L6, gFld("Myrmecophaga", "treeview_taxa.html?pic=%22Myrmecophaga%2Ejpg%22"))
insDoc(L7, gLnk("S", "Myrmecophaga_tridactyla", "http://www.bio.vu.nl/thb/deb/deblab/add_my_pet/entries_web/Myrmecophaga_tridactyla_res.html"))
L5 = insFld(L4, gFld("Cingulata", "treeview_taxa.html?pic=%22Cingulata%2Ejpg%22"))
L6 = insFld(L5, gFld("Dasypodidae", "treeview_taxa.html?pic=%22Dasypodidae%2Ejpg%22"))
L7 = insFld(L6, gFld("Dasypus", "treeview_taxa.html?pic=%22Dasypus%2Ejpg%22"))
insDoc(L7, gLnk("S", "Dasypus_novemcinctus", "http://www.bio.vu.nl/thb/deb/deblab/add_my_pet/entries_web/Dasypus_novemcinctus_res.html"))
L4 = insFld(L3, gFld("Afrotheria", "treeview_taxa.html?pic=%22Afrotheria%2Ejpg%22"))
L5 = insFld(L4, gFld("Afroinsectiphilia", "treeview_taxa.html?pic=%22Afroinsectiphilia%2Ejpg%22"))
L6 = insFld(L5, gFld("Tubulidentata", "treeview_taxa.html?pic=%22Tubulidentata%2Ejpg%22"))
L7 = insFld(L6, gFld("Orycteropodidae", "treeview_taxa.html?pic=%22Orycteropodidae%2Ejpg%22"))
L8 = insFld(L7, gFld("Orycteropus", "treeview_taxa.html?pic=%22Orycteropus%2Ejpg%22"))
insDoc(L8, gLnk("S", "Orycteropus_afer", "http://www.bio.vu.nl/thb/deb/deblab/add_my_pet/entries_web/Orycteropus_afer_res.html"))
L6 = insFld(L5, gFld("Macroscelidea", "treeview_taxa.html?pic=%22Macroscelidea%2Ejpg%22"))
L7 = insFld(L6, gFld("Macroscelididae", "treeview_taxa.html?pic=%22Macroscelididae%2Ejpg%22"))
L8 = insFld(L7, gFld("Macroscelides", "treeview_taxa.html?pic=%22Macroscelides%2Ejpg%22"))
insDoc(L8, gLnk("S", "Macroscelides_proboscideus", "http://www.bio.vu.nl/thb/deb/deblab/add_my_pet/entries_web/Macroscelides_proboscideus_res.html"))
L6 = insFld(L5, gFld("Afrosoricida", "treeview_taxa.html?pic=%22Afrosoricida%2Ejpg%22"))
L7 = insFld(L6, gFld("Tenrecidae", "treeview_taxa.html?pic=%22Tenrecidae%2Ejpg%22"))
L8 = insFld(L7, gFld("Hemicentetes", "treeview_taxa.html?pic=%22Hemicentetes%2Ejpg%22"))
insDoc(L8, gLnk("S", "Hemicentetes_semispinosus", "http://www.bio.vu.nl/thb/deb/deblab/add_my_pet/entries_web/Hemicentetes_semispinosus_res.html"))
L5 = insFld(L4, gFld("Paenungulata", "treeview_taxa.html?pic=%22Paenungulata%2Ejpg%22"))
L6 = insFld(L5, gFld("Proboscidea", "treeview_taxa.html?pic=%22Proboscidea%2Ejpg%22"))
L7 = insFld(L6, gFld("Elephantidae", "treeview_taxa.html?pic=%22Elephantidae%2Ejpg%22"))
L8 = insFld(L7, gFld("Loxodonta", "treeview_taxa.html?pic=%22Loxodonta%2Ejpg%22"))
insDoc(L8, gLnk("S", "Loxodonta_africana", "http://www.bio.vu.nl/thb/deb/deblab/add_my_pet/entries_web/Loxodonta_africana_res.html"))
L8 = insFld(L7, gFld("Elephas", "treeview_taxa.html?pic=%22Elephas%2Ejpg%22"))
insDoc(L8, gLnk("S", "Elephas_maximus", "http://www.bio.vu.nl/thb/deb/deblab/add_my_pet/entries_web/Elephas_maximus_res.html"))
L6 = insFld(L5, gFld("Sirenia", "treeview_taxa.html?pic=%22Sirenia%2Ejpg%22"))
L7 = insFld(L6, gFld("Trichechidae", "treeview_taxa.html?pic=%22Trichechidae%2Ejpg%22"))
L8 = insFld(L7, gFld("Trichechus", "treeview_taxa.html?pic=%22Trichechus%2Ejpg%22"))
insDoc(L8, gLnk("S", "Trichechus_inunguis", "http://www.bio.vu.nl/thb/deb/deblab/add_my_pet/entries_web/Trichechus_inunguis_res.html"))
L6 = insFld(L5, gFld("Hyracoidea", "treeview_taxa.html?pic=%22Hyracoidea%2Ejpg%22"))
L7 = insFld(L6, gFld("Procaviidae", "treeview_taxa.html?pic=%22Procaviidae%2Ejpg%22"))
L8 = insFld(L7, gFld("Procavia", "treeview_taxa.html?pic=%22Procavia%2Ejpg%22"))
insDoc(L8, gLnk("S", "Procavia_capensis", "http://www.bio.vu.nl/thb/deb/deblab/add_my_pet/entries_web/Procavia_capensis_res.html"))
L4 = insFld(L3, gFld("Boreoeutheria", "treeview_taxa.html?pic=%22Boreoeutheria%2Ejpg%22"))
L5 = insFld(L4, gFld("Laurasiatheria", "treeview_taxa.html?pic=%22Laurasiatheria%2Ejpg%22"))
L6 = insFld(L5, gFld("Eulipotyphla", "treeview_taxa.html?pic=%22Eulipotyphla%2Ejpg%22"))
L7 = insFld(L6, gFld("Soricidae", "treeview_taxa.html?pic=%22Soricidae%2Ejpg%22"))
L8 = insFld(L7, gFld("Sorex", "treeview_taxa.html?pic=%22Sorex%2Ejpg%22"))
insDoc(L8, gLnk("S", "Sorex_araneus", "http://www.bio.vu.nl/thb/deb/deblab/add_my_pet/entries_web/Sorex_araneus_res.html"))
L7 = insFld(L6, gFld("Talpidae", "treeview_taxa.html?pic=%22Talpidae%2Ejpg%22"))
L8 = insFld(L7, gFld("Talpa", "treeview_taxa.html?pic=%22Talpa%2Ejpg%22"))
insDoc(L8, gLnk("S", "Talpa_europaea", "http://www.bio.vu.nl/thb/deb/deblab/add_my_pet/entries_web/Talpa_europaea_res.html"))
insDoc(L8, gLnk("S", "Talpa_occidentalis", "http://www.bio.vu.nl/thb/deb/deblab/add_my_pet/entries_web/Talpa_occidentalis_res.html"))
L7 = insFld(L6, gFld("Erinaceidae", "treeview_taxa.html?pic=%22Erinaceidae%2Ejpg%22"))
L8 = insFld(L7, gFld("Erinaceus", "treeview_taxa.html?pic=%22Erinaceus%2Ejpg%22"))
insDoc(L8, gLnk("S", "Erinaceus_europaeus", "http://www.bio.vu.nl/thb/deb/deblab/add_my_pet/entries_web/Erinaceus_europaeus_res.html"))
L6 = insFld(L5, gFld("Ferungulata", "treeview_taxa.html?pic=%22Ferungulata%2Ejpg%22"))
L7 = insFld(L6, gFld("Cetartiodactyla", "treeview_taxa.html?pic=%22Cetartiodactyla%2Ejpg%22"))
L8 = insFld(L7, gFld("Tylopoda", "treeview_taxa.html?pic=%22Tylopoda%2Ejpg%22"))
L9 = insFld(L8, gFld("Camelidae", "treeview_taxa.html?pic=%22Camelidae%2Ejpg%22"))
L10 = insFld(L9, gFld("Camelus", "treeview_taxa.html?pic=%22Camelus%2Ejpg%22"))
insDoc(L10, gLnk("S", "Camelus_dromedarius", "http://www.bio.vu.nl/thb/deb/deblab/add_my_pet/entries_web/Camelus_dromedarius_res.html"))
L8 = insFld(L7, gFld("Artiofabula", "treeview_taxa.html?pic=%22Artiofabula%2Ejpg%22"))
L9 = insFld(L8, gFld("Suina", "treeview_taxa.html?pic=%22Suina%2Ejpg%22"))
L10 = insFld(L9, gFld("Suidae", "treeview_taxa.html?pic=%22Suidae%2Ejpg%22"))
L11 = insFld(L10, gFld("Sus", "treeview_taxa.html?pic=%22Sus%2Ejpg%22"))
insDoc(L11, gLnk("S", "Sus_scrofa", "http://www.bio.vu.nl/thb/deb/deblab/add_my_pet/entries_web/Sus_scrofa_res.html"))
L9 = insFld(L8, gFld("Centruminantia", "treeview_taxa.html?pic=%22Centruminantia%2Ejpg%22"))
L10 = insFld(L9, gFld("Cetancodontamorpha", "treeview_taxa.html?pic=%22Cetancodontamorpha%2Ejpg%22"))
L11 = insFld(L10, gFld("Cetacea", "treeview_taxa.html?pic=%22Cetacea%2Ejpg%22"))
L12 = insFld(L11, gFld("Odontoceti", "treeview_taxa.html?pic=%22Odontoceti%2Ejpg%22"))
L13 = insFld(L12, gFld("Monodontidae", "treeview_taxa.html?pic=%22Monodontidae%2Ejpg%22"))
L14 = insFld(L13, gFld("Monodon", "treeview_taxa.html?pic=%22Monodon%2Ejpg%22"))
insDoc(L14, gLnk("S", "Monodon_monoceros", "http://www.bio.vu.nl/thb/deb/deblab/add_my_pet/entries_web/Monodon_monoceros_res.html"))
L14 = insFld(L13, gFld("Delphinapterus", "treeview_taxa.html?pic=%22Delphinapterus%2Ejpg%22"))
insDoc(L14, gLnk("S", "Delphinapterus_leucas", "http://www.bio.vu.nl/thb/deb/deblab/add_my_pet/entries_web/Delphinapterus_leucas_res.html"))
L13 = insFld(L12, gFld("Phocoenidae", "treeview_taxa.html?pic=%22Phocoenidae%2Ejpg%22"))
L14 = insFld(L13, gFld("Phocoena", "treeview_taxa.html?pic=%22Phocoena%2Ejpg%22"))
insDoc(L14, gLnk("S", "Phocoena_phocoena", "http://www.bio.vu.nl/thb/deb/deblab/add_my_pet/entries_web/Phocoena_phocoena_res.html"))
L13 = insFld(L12, gFld("Delphinidae", "treeview_taxa.html?pic=%22Delphinidae%2Ejpg%22"))
L14 = insFld(L13, gFld("Delphinus", "treeview_taxa.html?pic=%22Delphinus%2Ejpg%22"))
insDoc(L14, gLnk("S", "Delphinus_delphis", "http://www.bio.vu.nl/thb/deb/deblab/add_my_pet/entries_web/Delphinus_delphis_res.html"))
L14 = insFld(L13, gFld("Tursiops", "treeview_taxa.html?pic=%22Tursiops%2Ejpg%22"))
insDoc(L14, gLnk("S", "Tursiops_truncatus", "http://www.bio.vu.nl/thb/deb/deblab/add_my_pet/entries_web/Tursiops_truncatus_res.html"))
L14 = insFld(L13, gFld("Pseudorca", "treeview_taxa.html?pic=%22Pseudorca%2Ejpg%22"))
insDoc(L14, gLnk("S", "Pseudorca_crassidens", "http://www.bio.vu.nl/thb/deb/deblab/add_my_pet/entries_web/Pseudorca_crassidens_res.html"))
L14 = insFld(L13, gFld("Orcinus", "treeview_taxa.html?pic=%22Orcinus%2Ejpg%22"))
insDoc(L14, gLnk("S", "Orcinus_orca", "http://www.bio.vu.nl/thb/deb/deblab/add_my_pet/entries_web/Orcinus_orca_res.html"))
L13 = insFld(L12, gFld("Pontoporiidae", "treeview_taxa.html?pic=%22Pontoporiidae%2Ejpg%22"))
L14 = insFld(L13, gFld("Pontoporia", "treeview_taxa.html?pic=%22Pontoporia%2Ejpg%22"))
insDoc(L14, gLnk("S", "Pontoporia_blainvillei", "http://www.bio.vu.nl/thb/deb/deblab/add_my_pet/entries_web/Pontoporia_blainvillei_res.html"))
L13 = insFld(L12, gFld("Physeteridae", "treeview_taxa.html?pic=%22Physeteridae%2Ejpg%22"))
L14 = insFld(L13, gFld("Physeter", "treeview_taxa.html?pic=%22Physeter%2Ejpg%22"))
insDoc(L14, gLnk("S", "Physeter_macrocephalus", "http://www.bio.vu.nl/thb/deb/deblab/add_my_pet/entries_web/Physeter_macrocephalus_res.html"))
L13 = insFld(L12, gFld("Ziphiidae", "treeview_taxa.html?pic=%22Ziphiidae%2Ejpg%22"))
L14 = insFld(L13, gFld("Hyperoodon", "treeview_taxa.html?pic=%22Hyperoodon%2Ejpg%22"))
insDoc(L14, gLnk("S", "Hyperoodon_ampullatus", "http://www.bio.vu.nl/thb/deb/deblab/add_my_pet/entries_web/Hyperoodon_ampullatus_res.html"))
L12 = insFld(L11, gFld("Mysticeti", "treeview_taxa.html?pic=%22Mysticeti%2Ejpg%22"))
L13 = insFld(L12, gFld("Balaenopteridae", "treeview_taxa.html?pic=%22Balaenopteridae%2Ejpg%22"))
L14 = insFld(L13, gFld("Balaenoptera", "treeview_taxa.html?pic=%22Balaenoptera%2Ejpg%22"))
insDoc(L14, gLnk("S", "Balaenoptera_acutorostrata", "http://www.bio.vu.nl/thb/deb/deblab/add_my_pet/entries_web/Balaenoptera_acutorostrata_res.html"))
insDoc(L14, gLnk("S", "Balaenoptera_musculus", "http://www.bio.vu.nl/thb/deb/deblab/add_my_pet/entries_web/Balaenoptera_musculus_res.html"))
L13 = insFld(L12, gFld("Eschrichtiidae", "treeview_taxa.html?pic=%22Eschrichtiidae%2Ejpg%22"))
L14 = insFld(L13, gFld("Eschrichtius", "treeview_taxa.html?pic=%22Eschrichtius%2Ejpg%22"))
insDoc(L14, gLnk("S", "Eschrichtius_robustus", "http://www.bio.vu.nl/thb/deb/deblab/add_my_pet/entries_web/Eschrichtius_robustus_res.html"))
L13 = insFld(L12, gFld("Balaenidae", "treeview_taxa.html?pic=%22Balaenidae%2Ejpg%22"))
L14 = insFld(L13, gFld("Eubalaena", "treeview_taxa.html?pic=%22Eubalaena%2Ejpg%22"))
insDoc(L14, gLnk("S", "Eubalaena_glacialis", "http://www.bio.vu.nl/thb/deb/deblab/add_my_pet/entries_web/Eubalaena_glacialis_res.html"))
L14 = insFld(L13, gFld("Balaena", "treeview_taxa.html?pic=%22Balaena%2Ejpg%22"))
insDoc(L14, gLnk("S", "Balaena_mysticetus", "http://www.bio.vu.nl/thb/deb/deblab/add_my_pet/entries_web/Balaena_mysticetus_res.html"))
L11 = insFld(L10, gFld("Hippopotamidae", "treeview_taxa.html?pic=%22Hippopotamidae%2Ejpg%22"))
L12 = insFld(L11, gFld("Hippopotamus", "treeview_taxa.html?pic=%22Hippopotamus%2Ejpg%22"))
insDoc(L12, gLnk("S", "Hippopotamus_amphibius", "http://www.bio.vu.nl/thb/deb/deblab/add_my_pet/entries_web/Hippopotamus_amphibius_res.html"))
L10 = insFld(L9, gFld("Ruminantiamorpha", "treeview_taxa.html?pic=%22Ruminantiamorpha%2Ejpg%22"))
L11 = insFld(L10, gFld("Giraffidae", "treeview_taxa.html?pic=%22Giraffidae%2Ejpg%22"))
L12 = insFld(L11, gFld("Giraffa", "treeview_taxa.html?pic=%22Giraffa%2Ejpg%22"))
insDoc(L12, gLnk("S", "Giraffa_camelopardalis", "http://www.bio.vu.nl/thb/deb/deblab/add_my_pet/entries_web/Giraffa_camelopardalis_res.html"))
L11 = insFld(L10, gFld("Cervidae", "treeview_taxa.html?pic=%22Cervidae%2Ejpg%22"))
L12 = insFld(L11, gFld("Odocoileus", "treeview_taxa.html?pic=%22Odocoileus%2Ejpg%22"))
insDoc(L12, gLnk("S", "Odocoileus_virginianus", "http://www.bio.vu.nl/thb/deb/deblab/add_my_pet/entries_web/Odocoileus_virginianus_res.html"))
L12 = insFld(L11, gFld("Cervus", "treeview_taxa.html?pic=%22Cervus%2Ejpg%22"))
insDoc(L12, gLnk("S", "Cervus_canadensis", "http://www.bio.vu.nl/thb/deb/deblab/add_my_pet/entries_web/Cervus_canadensis_res.html"))
L12 = insFld(L11, gFld("Rangifer", "treeview_taxa.html?pic=%22Rangifer%2Ejpg%22"))
insDoc(L12, gLnk("S", "Rangifer_tarandus", "http://www.bio.vu.nl/thb/deb/deblab/add_my_pet/entries_web/Rangifer_tarandus_res.html"))
L12 = insFld(L11, gFld("Alces", "treeview_taxa.html?pic=%22Alces%2Ejpg%22"))
insDoc(L12, gLnk("S", "Alces_alces", "http://www.bio.vu.nl/thb/deb/deblab/add_my_pet/entries_web/Alces_alces_res.html"))
L11 = insFld(L10, gFld("Bovidae", "treeview_taxa.html?pic=%22Bovidae%2Ejpg%22"))
L12 = insFld(L11, gFld("Aepyceros", "treeview_taxa.html?pic=%22Aepyceros%2Ejpg%22"))
insDoc(L12, gLnk("S", "Aepyceros_melampus", "http://www.bio.vu.nl/thb/deb/deblab/add_my_pet/entries_web/Aepyceros_melampus_res.html"))
L12 = insFld(L11, gFld("Bos", "treeview_taxa.html?pic=%22Bos%2Ejpg%22"))
insDoc(L12, gLnk("S", "Bos_primigenius_Angus", "http://www.bio.vu.nl/thb/deb/deblab/add_my_pet/entries_web/Bos_primigenius_Angus_res.html"))
insDoc(L12, gLnk("S", "Bos_primigenius_Holstein", "http://www.bio.vu.nl/thb/deb/deblab/add_my_pet/entries_web/Bos_primigenius_Holstein_res.html"))
insDoc(L12, gLnk("S", "Bos_primigenius_Brahman", "http://www.bio.vu.nl/thb/deb/deblab/add_my_pet/entries_web/Bos_primigenius_Brahman_res.html"))
L12 = insFld(L11, gFld("Rupicapra", "treeview_taxa.html?pic=%22Rupicapra%2Ejpg%22"))
insDoc(L12, gLnk("S", "Rupicapra_rupicapra", "http://www.bio.vu.nl/thb/deb/deblab/add_my_pet/entries_web/Rupicapra_rupicapra_res.html"))
L12 = insFld(L11, gFld("Ovibos", "treeview_taxa.html?pic=%22Ovibos%2Ejpg%22"))
insDoc(L12, gLnk("S", "Ovibos_moschatus", "http://www.bio.vu.nl/thb/deb/deblab/add_my_pet/entries_web/Ovibos_moschatus_res.html"))
L7 = insFld(L6, gFld("Pegasoferae", "treeview_taxa.html?pic=%22Pegasoferae%2Ejpg%22"))
L8 = insFld(L7, gFld("Chiroptera", "treeview_taxa.html?pic=%22Chiroptera%2Ejpg%22"))
L9 = insFld(L8, gFld("Vespertilionidae", "treeview_taxa.html?pic=%22Vespertilionidae%2Ejpg%22"))
L10 = insFld(L9, gFld("Pipistrellus", "treeview_taxa.html?pic=%22Pipistrellus%2Ejpg%22"))
insDoc(L10, gLnk("S", "Pipistrellus_pipistrellus", "http://www.bio.vu.nl/thb/deb/deblab/add_my_pet/entries_web/Pipistrellus_pipistrellus_res.html"))
L9 = insFld(L8, gFld("Phyllostomidae", "treeview_taxa.html?pic=%22Phyllostomidae%2Ejpg%22"))
L10 = insFld(L9, gFld("Desmodus", "treeview_taxa.html?pic=%22Desmodus%2Ejpg%22"))
insDoc(L10, gLnk("S", "Desmodus_rotundus", "http://www.bio.vu.nl/thb/deb/deblab/add_my_pet/entries_web/Desmodus_rotundus_res.html"))
L10 = insFld(L9, gFld("Carollia", "treeview_taxa.html?pic=%22Carollia%2Ejpg%22"))
insDoc(L10, gLnk("S", "Carollia_perspicillata", "http://www.bio.vu.nl/thb/deb/deblab/add_my_pet/entries_web/Carollia_perspicillata_res.html"))
L8 = insFld(L7, gFld("Zooamata", "treeview_taxa.html?pic=%22Zooamata%2Ejpg%22"))
L9 = insFld(L8, gFld("Ferae", "treeview_taxa.html?pic=%22Ferae%2Ejpg%22"))
L10 = insFld(L9, gFld("Pholidota", "treeview_taxa.html?pic=%22Pholidota%2Ejpg%22"))
L11 = insFld(L10, gFld("Manidae", "treeview_taxa.html?pic=%22Manidae%2Ejpg%22"))
L12 = insFld(L11, gFld("Manis", "treeview_taxa.html?pic=%22Manis%2Ejpg%22"))
insDoc(L12, gLnk("S", "Manis_crassicaudata", "http://www.bio.vu.nl/thb/deb/deblab/add_my_pet/entries_web/Manis_crassicaudata_res.html"))
L10 = insFld(L9, gFld("Carnivora", "treeview_taxa.html?pic=%22Carnivora%2Ejpg%22"))
L11 = insFld(L10, gFld("Feliformia", "treeview_taxa.html?pic=%22Feliformia%2Ejpg%22"))
L12 = insFld(L11, gFld("Hyaenidae", "treeview_taxa.html?pic=%22Hyaenidae%2Ejpg%22"))
L13 = insFld(L12, gFld("Crocuta", "treeview_taxa.html?pic=%22Crocuta%2Ejpg%22"))
insDoc(L13, gLnk("S", "Crocuta_crocuta", "http://www.bio.vu.nl/thb/deb/deblab/add_my_pet/entries_web/Crocuta_crocuta_res.html"))
L12 = insFld(L11, gFld("Felidae", "treeview_taxa.html?pic=%22Felidae%2Ejpg%22"))
L13 = insFld(L12, gFld("Panthera", "treeview_taxa.html?pic=%22Panthera%2Ejpg%22"))
insDoc(L13, gLnk("S", "Panthera_leo", "http://www.bio.vu.nl/thb/deb/deblab/add_my_pet/entries_web/Panthera_leo_res.html"))
L11 = insFld(L10, gFld("Caniformia", "treeview_taxa.html?pic=%22Caniformia%2Ejpg%22"))
L12 = insFld(L11, gFld("Canidae", "treeview_taxa.html?pic=%22Canidae%2Ejpg%22"))
L13 = insFld(L12, gFld("Vulpes", "treeview_taxa.html?pic=%22Vulpes%2Ejpg%22"))
insDoc(L13, gLnk("S", "Vulpes_lagopus", "http://www.bio.vu.nl/thb/deb/deblab/add_my_pet/entries_web/Vulpes_lagopus_res.html"))
insDoc(L13, gLnk("S", "Vulpes_vulpes", "http://www.bio.vu.nl/thb/deb/deblab/add_my_pet/entries_web/Vulpes_vulpes_res.html"))
L13 = insFld(L12, gFld("Canis", "treeview_taxa.html?pic=%22Canis%2Ejpg%22"))
insDoc(L13, gLnk("S", "Canis_lupus", "http://www.bio.vu.nl/thb/deb/deblab/add_my_pet/entries_web/Canis_lupus_res.html"))
L12 = insFld(L11, gFld("Arctoidea", "treeview_taxa.html?pic=%22Arctoidea%2Ejpg%22"))
L13 = insFld(L12, gFld("Mustelidae", "treeview_taxa.html?pic=%22Mustelidae%2Ejpg%22"))
L14 = insFld(L13, gFld("Meles", "treeview_taxa.html?pic=%22Meles%2Ejpg%22"))
insDoc(L14, gLnk("S", "Meles_meles", "http://www.bio.vu.nl/thb/deb/deblab/add_my_pet/entries_web/Meles_meles_res.html"))
L14 = insFld(L13, gFld("Enhydra", "treeview_taxa.html?pic=%22Enhydra%2Ejpg%22"))
insDoc(L14, gLnk("S", "Enhydra_lutris", "http://www.bio.vu.nl/thb/deb/deblab/add_my_pet/entries_web/Enhydra_lutris_res.html"))
L14 = insFld(L13, gFld("Lutra", "treeview_taxa.html?pic=%22Lutra%2Ejpg%22"))
insDoc(L14, gLnk("S", "Lutra_lutra", "http://www.bio.vu.nl/thb/deb/deblab/add_my_pet/entries_web/Lutra_lutra_res.html"))
L13 = insFld(L12, gFld("Ursidae", "treeview_taxa.html?pic=%22Ursidae%2Ejpg%22"))
L14 = insFld(L13, gFld("Ursus", "treeview_taxa.html?pic=%22Ursus%2Ejpg%22"))
insDoc(L14, gLnk("S", "Ursus_arctos", "http://www.bio.vu.nl/thb/deb/deblab/add_my_pet/entries_web/Ursus_arctos_res.html"))
insDoc(L14, gLnk("S", "Ursus_maritimus", "http://www.bio.vu.nl/thb/deb/deblab/add_my_pet/entries_web/Ursus_maritimus_res.html"))
L14 = insFld(L13, gFld("Ailuropoda", "treeview_taxa.html?pic=%22Ailuropoda%2Ejpg%22"))
insDoc(L14, gLnk("S", "Ailuropoda_melanoleuca", "http://www.bio.vu.nl/thb/deb/deblab/add_my_pet/entries_web/Ailuropoda_melanoleuca_res.html"))
L13 = insFld(L12, gFld("Pinnipedia", "treeview_taxa.html?pic=%22Pinnipedia%2Ejpg%22"))
L14 = insFld(L13, gFld("Otariidae", "treeview_taxa.html?pic=%22Otariidae%2Ejpg%22"))
L15 = insFld(L14, gFld("Callorhinus", "treeview_taxa.html?pic=%22Callorhinus%2Ejpg%22"))
insDoc(L15, gLnk("S", "Callorhinus_ursinus", "http://www.bio.vu.nl/thb/deb/deblab/add_my_pet/entries_web/Callorhinus_ursinus_res.html"))
L15 = insFld(L14, gFld("Zalophus", "treeview_taxa.html?pic=%22Zalophus%2Ejpg%22"))
insDoc(L15, gLnk("S", "Zalophus_californianus", "http://www.bio.vu.nl/thb/deb/deblab/add_my_pet/entries_web/Zalophus_californianus_res.html"))
L15 = insFld(L14, gFld("Arctocephalus", "treeview_taxa.html?pic=%22Arctocephalus%2Ejpg%22"))
insDoc(L15, gLnk("S", "Arctocephalus_australis", "http://www.bio.vu.nl/thb/deb/deblab/add_my_pet/entries_web/Arctocephalus_australis_res.html"))
L15 = insFld(L14, gFld("Otaria", "treeview_taxa.html?pic=%22Otaria%2Ejpg%22"))
insDoc(L15, gLnk("S", "Otaria_flavescens", "http://www.bio.vu.nl/thb/deb/deblab/add_my_pet/entries_web/Otaria_flavescens_res.html"))
L14 = insFld(L13, gFld("Phocidae", "treeview_taxa.html?pic=%22Phocidae%2Ejpg%22"))
L15 = insFld(L14, gFld("Phoca", "treeview_taxa.html?pic=%22Phoca%2Ejpg%22"))
insDoc(L15, gLnk("S", "Phoca_vitulina", "http://www.bio.vu.nl/thb/deb/deblab/add_my_pet/entries_web/Phoca_vitulina_res.html"))
L15 = insFld(L14, gFld("Pusa", "treeview_taxa.html?pic=%22Pusa%2Ejpg%22"))
insDoc(L15, gLnk("S", "Pusa_hispida", "http://www.bio.vu.nl/thb/deb/deblab/add_my_pet/entries_web/Pusa_hispida_res.html"))
L15 = insFld(L14, gFld("Halichoerus", "treeview_taxa.html?pic=%22Halichoerus%2Ejpg%22"))
insDoc(L15, gLnk("S", "Halichoerus_grypus", "http://www.bio.vu.nl/thb/deb/deblab/add_my_pet/entries_web/Halichoerus_grypus_res.html"))
L15 = insFld(L14, gFld("Pagophilus", "treeview_taxa.html?pic=%22Pagophilus%2Ejpg%22"))
insDoc(L15, gLnk("S", "Pagophilus_groenlandicus", "http://www.bio.vu.nl/thb/deb/deblab/add_my_pet/entries_web/Pagophilus_groenlandicus_res.html"))
L15 = insFld(L14, gFld("Erignathus", "treeview_taxa.html?pic=%22Erignathus%2Ejpg%22"))
insDoc(L15, gLnk("S", "Erignathus_barbatus", "http://www.bio.vu.nl/thb/deb/deblab/add_my_pet/entries_web/Erignathus_barbatus_res.html"))
L15 = insFld(L14, gFld("Cystophora", "treeview_taxa.html?pic=%22Cystophora%2Ejpg%22"))
insDoc(L15, gLnk("S", "Cystophora_cristata", "http://www.bio.vu.nl/thb/deb/deblab/add_my_pet/entries_web/Cystophora_cristata_res.html"))
L15 = insFld(L14, gFld("Mirounga", "treeview_taxa.html?pic=%22Mirounga%2Ejpg%22"))
insDoc(L15, gLnk("S", "Mirounga_leonina", "http://www.bio.vu.nl/thb/deb/deblab/add_my_pet/entries_web/Mirounga_leonina_res.html"))
L14 = insFld(L13, gFld("Odobenidae", "treeview_taxa.html?pic=%22Odobenidae%2Ejpg%22"))
L15 = insFld(L14, gFld("Odobenus", "treeview_taxa.html?pic=%22Odobenus%2Ejpg%22"))
insDoc(L15, gLnk("S", "Odobenus_rosmarus_rosmarus", "http://www.bio.vu.nl/thb/deb/deblab/add_my_pet/entries_web/Odobenus_rosmarus_rosmarus_res.html"))
L9 = insFld(L8, gFld("Perissodactyla", "treeview_taxa.html?pic=%22Perissodactyla%2Ejpg%22"))
L10 = insFld(L9, gFld("Hippomorpha", "treeview_taxa.html?pic=%22Hippomorpha%2Ejpg%22"))
L11 = insFld(L10, gFld("Equidae", "treeview_taxa.html?pic=%22Equidae%2Ejpg%22"))
L12 = insFld(L11, gFld("Equus", "treeview_taxa.html?pic=%22Equus%2Ejpg%22"))
insDoc(L12, gLnk("S", "Equus_quagga", "http://www.bio.vu.nl/thb/deb/deblab/add_my_pet/entries_web/Equus_quagga_res.html"))
L10 = insFld(L9, gFld("Ceratomorpha", "treeview_taxa.html?pic=%22Ceratomorpha%2Ejpg%22"))
L11 = insFld(L10, gFld("Tapiridae", "treeview_taxa.html?pic=%22Tapiridae%2Ejpg%22"))
L12 = insFld(L11, gFld("Tapirus", "treeview_taxa.html?pic=%22Tapirus%2Ejpg%22"))
insDoc(L12, gLnk("S", "Tapirus_terrestris", "http://www.bio.vu.nl/thb/deb/deblab/add_my_pet/entries_web/Tapirus_terrestris_res.html"))
L11 = insFld(L10, gFld("Rhinocerotidae", "treeview_taxa.html?pic=%22Rhinocerotidae%2Ejpg%22"))
L12 = insFld(L11, gFld("Rhinoceros", "treeview_taxa.html?pic=%22Rhinoceros%2Ejpg%22"))
insDoc(L12, gLnk("S", "Rhinoceros_unicornis", "http://www.bio.vu.nl/thb/deb/deblab/add_my_pet/entries_web/Rhinoceros_unicornis_res.html"))
L12 = insFld(L11, gFld("Dicerorhinus", "treeview_taxa.html?pic=%22Dicerorhinus%2Ejpg%22"))
insDoc(L12, gLnk("S", "Dicerorhinus_sumatrensis", "http://www.bio.vu.nl/thb/deb/deblab/add_my_pet/entries_web/Dicerorhinus_sumatrensis_res.html"))
L12 = insFld(L11, gFld("Ceratotherium", "treeview_taxa.html?pic=%22Ceratotherium%2Ejpg%22"))
insDoc(L12, gLnk("S", "Ceratotherium_simum", "http://www.bio.vu.nl/thb/deb/deblab/add_my_pet/entries_web/Ceratotherium_simum_res.html"))
L5 = insFld(L4, gFld("Euarchontoglires", "treeview_taxa.html?pic=%22Euarchontoglires%2Ejpg%22"))
L6 = insFld(L5, gFld("Gliriformes", "treeview_taxa.html?pic=%22Gliriformes%2Ejpg%22"))
L7 = insFld(L6, gFld("Rodentia", "treeview_taxa.html?pic=%22Rodentia%2Ejpg%22"))
L8 = insFld(L7, gFld("Castorimorpha", "treeview_taxa.html?pic=%22Castorimorpha%2Ejpg%22"))
L9 = insFld(L8, gFld("Castoridae", "treeview_taxa.html?pic=%22Castoridae%2Ejpg%22"))
L10 = insFld(L9, gFld("Castor", "treeview_taxa.html?pic=%22Castor%2Ejpg%22"))
insDoc(L10, gLnk("S", "Castor_fiber", "http://www.bio.vu.nl/thb/deb/deblab/add_my_pet/entries_web/Castor_fiber_res.html"))
L8 = insFld(L7, gFld("Hystricomorpha", "treeview_taxa.html?pic=%22Hystricomorpha%2Ejpg%22"))
L9 = insFld(L8, gFld("Bathyergidae", "treeview_taxa.html?pic=%22Bathyergidae%2Ejpg%22"))
L10 = insFld(L9, gFld("Heterocephalus", "treeview_taxa.html?pic=%22Heterocephalus%2Ejpg%22"))
insDoc(L10, gLnk("S", "Heterocephalus_glaber", "http://www.bio.vu.nl/thb/deb/deblab/add_my_pet/entries_web/Heterocephalus_glaber_res.html"))
L9 = insFld(L8, gFld("Hystricidae", "treeview_taxa.html?pic=%22Hystricidae%2Ejpg%22"))
L10 = insFld(L9, gFld("Hystrix", "treeview_taxa.html?pic=%22Hystrix%2Ejpg%22"))
insDoc(L10, gLnk("S", "Hystrix_africaeaustralis", "http://www.bio.vu.nl/thb/deb/deblab/add_my_pet/entries_web/Hystrix_africaeaustralis_res.html"))
L9 = insFld(L8, gFld("Caviidae", "treeview_taxa.html?pic=%22Caviidae%2Ejpg%22"))
L10 = insFld(L9, gFld("Cavia", "treeview_taxa.html?pic=%22Cavia%2Ejpg%22"))
insDoc(L10, gLnk("S", "Cavia_tschudii", "http://www.bio.vu.nl/thb/deb/deblab/add_my_pet/entries_web/Cavia_tschudii_res.html"))
L10 = insFld(L9, gFld("Hydrochoerus", "treeview_taxa.html?pic=%22Hydrochoerus%2Ejpg%22"))
insDoc(L10, gLnk("S", "Hydrochoerus_hydrochaeris", "http://www.bio.vu.nl/thb/deb/deblab/add_my_pet/entries_web/Hydrochoerus_hydrochaeris_res.html"))
L9 = insFld(L8, gFld("Chinchillidae", "treeview_taxa.html?pic=%22Chinchillidae%2Ejpg%22"))
L10 = insFld(L9, gFld("Chinchilla", "treeview_taxa.html?pic=%22Chinchilla%2Ejpg%22"))
insDoc(L10, gLnk("S", "Chinchilla_lanigera", "http://www.bio.vu.nl/thb/deb/deblab/add_my_pet/entries_web/Chinchilla_lanigera_res.html"))
L8 = insFld(L7, gFld("Myomorpha", "treeview_taxa.html?pic=%22Myomorpha%2Ejpg%22"))
L9 = insFld(L8, gFld("Cricetidae", "treeview_taxa.html?pic=%22Cricetidae%2Ejpg%22"))
L10 = insFld(L9, gFld("Microtus", "treeview_taxa.html?pic=%22Microtus%2Ejpg%22"))
insDoc(L10, gLnk("S", "Microtus_arvalis", "http://www.bio.vu.nl/thb/deb/deblab/add_my_pet/entries_web/Microtus_arvalis_res.html"))
insDoc(L10, gLnk("S", "Microtus_cabrerae", "http://www.bio.vu.nl/thb/deb/deblab/add_my_pet/entries_web/Microtus_cabrerae_res.html"))
L10 = insFld(L9, gFld("Arvicola", "treeview_taxa.html?pic=%22Arvicola%2Ejpg%22"))
insDoc(L10, gLnk("S", "Arvicola_amphibius", "http://www.bio.vu.nl/thb/deb/deblab/add_my_pet/entries_web/Arvicola_amphibius_res.html"))
L9 = insFld(L8, gFld("Muridae", "treeview_taxa.html?pic=%22Muridae%2Ejpg%22"))
L10 = insFld(L9, gFld("Mus", "treeview_taxa.html?pic=%22Mus%2Ejpg%22"))
insDoc(L10, gLnk("S", "Mus_musculus", "http://www.bio.vu.nl/thb/deb/deblab/add_my_pet/entries_web/Mus_musculus_res.html"))
L10 = insFld(L9, gFld("Rattus", "treeview_taxa.html?pic=%22Rattus%2Ejpg%22"))
insDoc(L10, gLnk("S", "Rattus_norvegicus", "http://www.bio.vu.nl/thb/deb/deblab/add_my_pet/entries_web/Rattus_norvegicus_res.html"))
L10 = insFld(L9, gFld("Lemmus", "treeview_taxa.html?pic=%22Lemmus%2Ejpg%22"))
insDoc(L10, gLnk("S", "Lemmus_trimucronatus", "http://www.bio.vu.nl/thb/deb/deblab/add_my_pet/entries_web/Lemmus_trimucronatus_res.html"))
L8 = insFld(L7, gFld("Sciuromorpha", "treeview_taxa.html?pic=%22Sciuromorpha%2Ejpg%22"))
L9 = insFld(L8, gFld("Gliridae", "treeview_taxa.html?pic=%22Gliridae%2Ejpg%22"))
L10 = insFld(L9, gFld("Glis", "treeview_taxa.html?pic=%22Glis%2Ejpg%22"))
insDoc(L10, gLnk("S", "Glis_glis", "http://www.bio.vu.nl/thb/deb/deblab/add_my_pet/entries_web/Glis_glis_res.html"))
L9 = insFld(L8, gFld("Sciuridae", "treeview_taxa.html?pic=%22Sciuridae%2Ejpg%22"))
L10 = insFld(L9, gFld("Marmota", "treeview_taxa.html?pic=%22Marmota%2Ejpg%22"))
insDoc(L10, gLnk("S", "Marmota_flaviventris", "http://www.bio.vu.nl/thb/deb/deblab/add_my_pet/entries_web/Marmota_flaviventris_res.html"))
L7 = insFld(L6, gFld("Lagomorpha", "treeview_taxa.html?pic=%22Lagomorpha%2Ejpg%22"))
L8 = insFld(L7, gFld("Leporidae", "treeview_taxa.html?pic=%22Leporidae%2Ejpg%22"))
L9 = insFld(L8, gFld("Oryctolagus", "treeview_taxa.html?pic=%22Oryctolagus%2Ejpg%22"))
insDoc(L9, gLnk("S", "Oryctolagus_cuniculus", "http://www.bio.vu.nl/thb/deb/deblab/add_my_pet/entries_web/Oryctolagus_cuniculus_res.html"))
insDoc(L9, gLnk("S", "Oryctolagus_cuniculus_NZW", "http://www.bio.vu.nl/thb/deb/deblab/add_my_pet/entries_web/Oryctolagus_cuniculus_NZW_res.html"))
L9 = insFld(L8, gFld("Lepus", "treeview_taxa.html?pic=%22Lepus%2Ejpg%22"))
insDoc(L9, gLnk("S", "Lepus_europaeus", "http://www.bio.vu.nl/thb/deb/deblab/add_my_pet/entries_web/Lepus_europaeus_res.html"))
L6 = insFld(L5, gFld("Euarchonta", "treeview_taxa.html?pic=%22Euarchonta%2Ejpg%22"))
L7 = insFld(L6, gFld("Scandentia", "treeview_taxa.html?pic=%22Scandentia%2Ejpg%22"))
L8 = insFld(L7, gFld("Tupaiidae", "treeview_taxa.html?pic=%22Tupaiidae%2Ejpg%22"))
L9 = insFld(L8, gFld("Tupaia", "treeview_taxa.html?pic=%22Tupaia%2Ejpg%22"))
insDoc(L9, gLnk("S", "Tupaia_glis", "http://www.bio.vu.nl/thb/deb/deblab/add_my_pet/entries_web/Tupaia_glis_res.html"))
L7 = insFld(L6, gFld("Dermoptera", "treeview_taxa.html?pic=%22Dermoptera%2Ejpg%22"))
L8 = insFld(L7, gFld("Cynocephaldae", "treeview_taxa.html?pic=%22Cynocephaldae%2Ejpg%22"))
L9 = insFld(L8, gFld("Galeopterus", "treeview_taxa.html?pic=%22Galeopterus%2Ejpg%22"))
insDoc(L9, gLnk("S", "Galeopterus_variegatus", "http://www.bio.vu.nl/thb/deb/deblab/add_my_pet/entries_web/Galeopterus_variegatus_res.html"))
L7 = insFld(L6, gFld("Primates", "treeview_taxa.html?pic=%22Primates%2Ejpg%22"))
L8 = insFld(L7, gFld("Lemuriformes", "treeview_taxa.html?pic=%22Lemuriformes%2Ejpg%22"))
L9 = insFld(L8, gFld("Lemuroidea", "treeview_taxa.html?pic=%22Lemuroidea%2Ejpg%22"))
L10 = insFld(L9, gFld("Daubentoniidae", "treeview_taxa.html?pic=%22Daubentoniidae%2Ejpg%22"))
L11 = insFld(L10, gFld("Daubentonia", "treeview_taxa.html?pic=%22Daubentonia%2Ejpg%22"))
insDoc(L11, gLnk("S", "Daubentonia_madagascariensis", "http://www.bio.vu.nl/thb/deb/deblab/add_my_pet/entries_web/Daubentonia_madagascariensis_res.html"))
L10 = insFld(L9, gFld("Indriidae", "treeview_taxa.html?pic=%22Indriidae%2Ejpg%22"))
L11 = insFld(L10, gFld("Propithecus", "treeview_taxa.html?pic=%22Propithecus%2Ejpg%22"))
insDoc(L11, gLnk("S", "Propithecus_diadema", "http://www.bio.vu.nl/thb/deb/deblab/add_my_pet/entries_web/Propithecus_diadema_res.html"))
L10 = insFld(L9, gFld("Cheirogaleidae", "treeview_taxa.html?pic=%22Cheirogaleidae%2Ejpg%22"))
L11 = insFld(L10, gFld("Microcebus", "treeview_taxa.html?pic=%22Microcebus%2Ejpg%22"))
insDoc(L11, gLnk("S", "Microcebus_murinus", "http://www.bio.vu.nl/thb/deb/deblab/add_my_pet/entries_web/Microcebus_murinus_res.html"))
L10 = insFld(L9, gFld("Lepilemuridae", "treeview_taxa.html?pic=%22Lepilemuridae%2Ejpg%22"))
L11 = insFld(L10, gFld("Lepilemur", "treeview_taxa.html?pic=%22Lepilemur%2Ejpg%22"))
insDoc(L11, gLnk("S", "Lepilemur_mustelinus", "http://www.bio.vu.nl/thb/deb/deblab/add_my_pet/entries_web/Lepilemur_mustelinus_res.html"))
L10 = insFld(L9, gFld("Lemuridae", "treeview_taxa.html?pic=%22Lemuridae%2Ejpg%22"))
L11 = insFld(L10, gFld("Varecia", "treeview_taxa.html?pic=%22Varecia%2Ejpg%22"))
insDoc(L11, gLnk("S", "Varecia_variegata", "http://www.bio.vu.nl/thb/deb/deblab/add_my_pet/entries_web/Varecia_variegata_res.html"))
L9 = insFld(L8, gFld("Lorisoidea", "treeview_taxa.html?pic=%22Lorisoidea%2Ejpg%22"))
L10 = insFld(L9, gFld("Lorisidae", "treeview_taxa.html?pic=%22Lorisidae%2Ejpg%22"))
L11 = insFld(L10, gFld("Nycticebus", "treeview_taxa.html?pic=%22Nycticebus%2Ejpg%22"))
insDoc(L11, gLnk("S", "Nycticebus_coucang", "http://www.bio.vu.nl/thb/deb/deblab/add_my_pet/entries_web/Nycticebus_coucang_res.html"))
L11 = insFld(L10, gFld("Loris", "treeview_taxa.html?pic=%22Loris%2Ejpg%22"))
insDoc(L11, gLnk("S", "Loris_tardigradus", "http://www.bio.vu.nl/thb/deb/deblab/add_my_pet/entries_web/Loris_tardigradus_res.html"))
L10 = insFld(L9, gFld("Galagidae", "treeview_taxa.html?pic=%22Galagidae%2Ejpg%22"))
L11 = insFld(L10, gFld("Galago", "treeview_taxa.html?pic=%22Galago%2Ejpg%22"))
insDoc(L11, gLnk("S", "Galago_senegalensis", "http://www.bio.vu.nl/thb/deb/deblab/add_my_pet/entries_web/Galago_senegalensis_res.html"))
L8 = insFld(L7, gFld("Haplorhini", "treeview_taxa.html?pic=%22Haplorhini%2Ejpg%22"))
L9 = insFld(L8, gFld("Tarsiiformes", "treeview_taxa.html?pic=%22Tarsiiformes%2Ejpg%22"))
L10 = insFld(L9, gFld("Tarsiidae", "treeview_taxa.html?pic=%22Tarsiidae%2Ejpg%22"))
L11 = insFld(L10, gFld("Tarsius", "treeview_taxa.html?pic=%22Tarsius%2Ejpg%22"))
insDoc(L11, gLnk("S", "Tarsius_tarsier", "http://www.bio.vu.nl/thb/deb/deblab/add_my_pet/entries_web/Tarsius_tarsier_res.html"))
L9 = insFld(L8, gFld("Simiiformes", "treeview_taxa.html?pic=%22Simiiformes%2Ejpg%22"))
L10 = insFld(L9, gFld("Platyrrhini", "treeview_taxa.html?pic=%22Platyrrhini%2Ejpg%22"))
L11 = insFld(L10, gFld("Callitrichidae", "treeview_taxa.html?pic=%22Callitrichidae%2Ejpg%22"))
L12 = insFld(L11, gFld("Callithrix", "treeview_taxa.html?pic=%22Callithrix%2Ejpg%22"))
insDoc(L12, gLnk("S", "Callithrix_pygmaea", "http://www.bio.vu.nl/thb/deb/deblab/add_my_pet/entries_web/Callithrix_pygmaea_res.html"))
insDoc(L12, gLnk("S", "Callithrix_jacchus", "http://www.bio.vu.nl/thb/deb/deblab/add_my_pet/entries_web/Callithrix_jacchus_res.html"))
L12 = insFld(L11, gFld("Leontopithecus", "treeview_taxa.html?pic=%22Leontopithecus%2Ejpg%22"))
insDoc(L12, gLnk("S", "Leontopithecus_rosalia", "http://www.bio.vu.nl/thb/deb/deblab/add_my_pet/entries_web/Leontopithecus_rosalia_res.html"))
L11 = insFld(L10, gFld("Aotidae", "treeview_taxa.html?pic=%22Aotidae%2Ejpg%22"))
L12 = insFld(L11, gFld("Aotus", "treeview_taxa.html?pic=%22Aotus%2Ejpg%22"))
insDoc(L12, gLnk("S", "Aotus_trivirgatus", "http://www.bio.vu.nl/thb/deb/deblab/add_my_pet/entries_web/Aotus_trivirgatus_res.html"))
L11 = insFld(L10, gFld("Pitheciidae", "treeview_taxa.html?pic=%22Pitheciidae%2Ejpg%22"))
L12 = insFld(L11, gFld("Pithecia", "treeview_taxa.html?pic=%22Pithecia%2Ejpg%22"))
insDoc(L12, gLnk("S", "Pithecia_pithecia", "http://www.bio.vu.nl/thb/deb/deblab/add_my_pet/entries_web/Pithecia_pithecia_res.html"))
L11 = insFld(L10, gFld("Cebidae", "treeview_taxa.html?pic=%22Cebidae%2Ejpg%22"))
L12 = insFld(L11, gFld("Cebus", "treeview_taxa.html?pic=%22Cebus%2Ejpg%22"))
insDoc(L12, gLnk("S", "Cebus_capucinus", "http://www.bio.vu.nl/thb/deb/deblab/add_my_pet/entries_web/Cebus_capucinus_res.html"))
L12 = insFld(L11, gFld("Saimiri", "treeview_taxa.html?pic=%22Saimiri%2Ejpg%22"))
insDoc(L12, gLnk("S", "Saimiri_sciureus", "http://www.bio.vu.nl/thb/deb/deblab/add_my_pet/entries_web/Saimiri_sciureus_res.html"))
L11 = insFld(L10, gFld("Atelidae", "treeview_taxa.html?pic=%22Atelidae%2Ejpg%22"))
L12 = insFld(L11, gFld("Alouatta", "treeview_taxa.html?pic=%22Alouatta%2Ejpg%22"))
insDoc(L12, gLnk("S", "Alouatta_palliata", "http://www.bio.vu.nl/thb/deb/deblab/add_my_pet/entries_web/Alouatta_palliata_res.html"))
L10 = insFld(L9, gFld("Catarrhini", "treeview_taxa.html?pic=%22Catarrhini%2Ejpg%22"))
L11 = insFld(L10, gFld("Cercopithecoidea", "treeview_taxa.html?pic=%22Cercopithecoidea%2Ejpg%22"))
L12 = insFld(L11, gFld("Cercopithecidae", "treeview_taxa.html?pic=%22Cercopithecidae%2Ejpg%22"))
L13 = insFld(L12, gFld("Chlorocebus", "treeview_taxa.html?pic=%22Chlorocebus%2Ejpg%22"))
insDoc(L13, gLnk("S", "Chlorocebus_aethiops", "http://www.bio.vu.nl/thb/deb/deblab/add_my_pet/entries_web/Chlorocebus_aethiops_res.html"))
L13 = insFld(L12, gFld("Papio", "treeview_taxa.html?pic=%22Papio%2Ejpg%22"))
insDoc(L13, gLnk("S", "Papio_hamadryas", "http://www.bio.vu.nl/thb/deb/deblab/add_my_pet/entries_web/Papio_hamadryas_res.html"))
L13 = insFld(L12, gFld("Nasalis", "treeview_taxa.html?pic=%22Nasalis%2Ejpg%22"))
insDoc(L13, gLnk("S", "Nasalis_larvatus", "http://www.bio.vu.nl/thb/deb/deblab/add_my_pet/entries_web/Nasalis_larvatus_res.html"))
L13 = insFld(L12, gFld("Macaca", "treeview_taxa.html?pic=%22Macaca%2Ejpg%22"))
insDoc(L13, gLnk("S", "Macaca_fascicularis", "http://www.bio.vu.nl/thb/deb/deblab/add_my_pet/entries_web/Macaca_fascicularis_res.html"))
insDoc(L13, gLnk("S", "Macaca_mulatta", "http://www.bio.vu.nl/thb/deb/deblab/add_my_pet/entries_web/Macaca_mulatta_res.html"))
L11 = insFld(L10, gFld("Hominoidea", "treeview_taxa.html?pic=%22Hominoidea%2Ejpg%22"))
L12 = insFld(L11, gFld("Hylobatidae", "treeview_taxa.html?pic=%22Hylobatidae%2Ejpg%22"))
L13 = insFld(L12, gFld("Hylobates", "treeview_taxa.html?pic=%22Hylobates%2Ejpg%22"))
insDoc(L13, gLnk("S", "Hylobates_lar", "http://www.bio.vu.nl/thb/deb/deblab/add_my_pet/entries_web/Hylobates_lar_res.html"))
L13 = insFld(L12, gFld("Symphalangus", "treeview_taxa.html?pic=%22Symphalangus%2Ejpg%22"))
insDoc(L13, gLnk("S", "Symphalangus_syndactylus", "http://www.bio.vu.nl/thb/deb/deblab/add_my_pet/entries_web/Symphalangus_syndactylus_res.html"))
L12 = insFld(L11, gFld("Hominidae", "treeview_taxa.html?pic=%22Hominidae%2Ejpg%22"))
L13 = insFld(L12, gFld("Pongo", "treeview_taxa.html?pic=%22Pongo%2Ejpg%22"))
insDoc(L13, gLnk("S", "Pongo_pygmaeus", "http://www.bio.vu.nl/thb/deb/deblab/add_my_pet/entries_web/Pongo_pygmaeus_res.html"))
L13 = insFld(L12, gFld("Gorilla", "treeview_taxa.html?pic=%22Gorilla%2Ejpg%22"))
insDoc(L13, gLnk("S", "Gorilla_gorilla", "http://www.bio.vu.nl/thb/deb/deblab/add_my_pet/entries_web/Gorilla_gorilla_res.html"))
L13 = insFld(L12, gFld("Pan", "treeview_taxa.html?pic=%22Pan%2Ejpg%22"))
insDoc(L13, gLnk("S", "Pan_troglodytes", "http://www.bio.vu.nl/thb/deb/deblab/add_my_pet/entries_web/Pan_troglodytes_res.html"))
L13 = insFld(L12, gFld("Homo", "treeview_taxa.html?pic=%22Homo%2Ejpg%22"))
insDoc(L13, gLnk("S", "Homo_sapiens", "http://www.bio.vu.nl/thb/deb/deblab/add_my_pet/entries_web/Homo_sapiens_res.html"))
foldersTree.treeID = "Mammalia"
