%% get_statfields
% returns cell array of strings with names of statistics and a stucture
% with color fields which are needed for the web for a given DEB model

%%
function [webStatFields, webColStat]= get_statfields(model)
% created 2016/09/21 by Starrlight Augustine
 
  %% Syntax 
  % [webStatFields, webColStat] = <../get_statfields.m *get_statfields*> (model)

  %% Description
  % Provides the list of fields in statistics in the order that they should
  % be printed to the wb
  %
  % Input
  %
  % * model: string with name of model: 'std', 'stf', 'stx', 'ssj', 'sbp', 'abj', 'asj', 'abp', 'hep', 'hex'. 
  %
  % Output
  %
  % * webStatFields: cell string with field names
  % * webColStat: structure with associated colors for each field name
  
  %% Remarks
  % Only applies to generating webpages - change here if we could like to
  % see other things on the web and/ or wish to change the order they
  % appear in on the web

  %% Example of use
  % [webStatFields, webColStat] = get_parfields(metaPar.model)
  
  webColStat.z        = '#FFC6A5';
  webColStat.s_Hbp    = '#F7BDDE'; webColStat.s_HLbp = '#F7BDDE'; webColStat.s_s   = '#F7BDDE';
  webColStat.c_T      = '#FFC6A5';
  webColStat.E_0      = '#FFFFFF';  
  webColStat.Wd_0     = '#FFFFFF';  
  webColStat.a_b      = '#C6E7DE'; webColStat.t_g   = '#C6E7DE';
  webColStat.a_p      = '#C6E7DE'; webColStat.a_99  = '#C6E7DE';
  webColStat.Wd_b     = '#CEEFBD'; webColStat.Wd_p  = '#CEEFBD'; webColStat.Wd_i = '#CEEFBD';
  webColStat.L_b      = '#DEF3BD'; webColStat.L_p   = '#DEF3BD'; webColStat.L_i   = '#DEF3BD'; 
  
  webColStat.W_dWm    = '#FFFFFF'; webColStat.dWm   = '#FFFFFF';
  
  webColStat.R_i      = '#FFFFC6'; webColStat.N_i   = '#FFFFC6'; 
 
  webColStat.del_Wb   = '#FFFF9C';  webColStat.del_Wp   = '#FFFF9C';  webColStat.del_V = '#FFFF9C'; webColStat.r_B = '#FFFF9C'; 
  webColStat.E_m      = '#FFC6A5';  webColStat.t_starve = '#FFC6A5';  webColStat.t_E = '#FFC6A5';  webColStat.xi_WE = '#FFC6A5'; 
  webColStat.eb_min_G = '#94D6E7';  webColStat.eb_min_R = '#94D6E7'; % webColStat.ep_min = '#94D6E7';
  webColStat.J_Ob     = '#FFFFFF';  webColStat.J_Op     = '#FFFFFF'; webColStat.J_Oi = '#FFFFFF';

  webColStat.s_M  = '#F7BDDE'; 
  webColStat.a_j  = webColStat.a_b;  webColStat.L_j = webColStat.L_b;  webColStat.Wd_j = webColStat.Wd_b; 
  webColStat.J_Oj = webColStat.J_Ob;  %webColStat.p_t_j = webColStat.p_t_b; webColStat.RQ_j = webColStat.RQ_b;

  
  
  switch model
      
  case {'std', 'abp', 'sbp'}      
    webStatFields =  {...
    'z'; 'c_T'; ...
    's_Hbp'; 's_HLbp'; 's_s'; ...
    'E_0';'Wd_0'; ...
    'a_b'; 'a_p'; 'a_99'; ...
    'Wd_b'; 'Wd_p'; 'Wd_i'; 'L_b';'L_p'; 'L_i'; ...
    'W_dWm'; 'dWm'; ...
    'R_i'; 'N_i'; ...
    'del_Wb'; 'del_Wp'; 'del_V'; 'r_B'; ...
    'E_m'; 't_starve'; 't_E'; 'xi_WE'; ...
    'eb_min_G'; 'eb_min_R'; ... 'ep_min'; ...
    'J_Ob'; 'J_Op'; 'J_Oi'};
    
  case {'stx', 'stf'}     
    webStatFields =  {...
    'z';  'c_T'; ...
    's_Hbp'; 's_HLbp'; 's_s'; ...
    'a_b'; 't_g'; 'a_p'; 'a_99'; ...
    'Wd_b'; 'Wd_p'; 'Wd_i'; 'L_b';'L_p'; 'L_i'; ...
    'W_dWm'; 'dWm'; ...
    'R_i'; 'N_i'; ...
    'del_Wb'; 'del_Wp'; 'del_V'; 'r_B'; ...
    'E_m'; 't_starve'; 't_E'; 'xi_WE'; ...
    %'eb_min_G'; 'eb_min_R'; ... 'ep_min'; ...
    'J_Ob'; 'J_Op'; 'J_Oi'};  

  case 'ssj'
     webStatFields =  {...
    'z'; 'c_T'; ...
    's_Hbp'; 's_HLbp'; 's_s'; ...
    'E_0';'Wd_0'; ...
    'a_b'; 'a_p'; 'a_99'; ...
    'Wd_b'; 'Wd_p'; 'Wd_i'; 'L_b';'L_p'; 'L_i'; ...
    'W_dWm'; 'dWm'; ...
    'R_i'; 'N_i'; ...
    'del_Wb'; 'del_Wp'; 'del_V'; 'r_B'; ...
    'E_m'; 't_starve'; 't_E'; 'xi_WE'; ...
    'eb_min_G'; 'eb_min_R'; ... 'ep_min'; ...
    'J_Ob'; 'J_Op'; 'J_Oi'};

  case 'abj'
    webStatFields =  {...
    'z'; 'c_T'; ...
    's_M'; 's_Hbp'; 's_HLbp'; 's_s'; ...
   'E_0'; 'Wd_0'; ...
    'a_b'; 'a_p'; 'a_99'; ...
    'Wd_b'; 'Wd_p'; 'Wd_i'; 'L_b';'L_p'; 'L_i'; ...
    'W_dWm'; 'dWm'; ...
    'N_i'; 'R_i';  ...
    'del_Wb'; 'del_Wp'; 'del_V'; 'r_B'; ...
    'E_m'; 't_starve'; 't_E'; 'xi_WE'; ...
    'eb_min_G'; 'eb_min_R'; ... 'ep_min'; ...
    'J_Ob'; 'J_Op'; 'J_Oi'};

 
    
  case 'asj'
     webStatFields =  {...
    'z'; 'c_T'; ...
    's_M'; 's_Hbp'; 's_HLbp'; 's_s'; ...
    'E_0';'Wd_0'; ...
    'a_b'; 'a_p'; 'a_99'; ...
    'Wd_b'; 'Wd_p'; 'Wd_i'; 'L_b';'L_p'; 'L_i'; ...
    'W_dWm'; 'dWm'; ...
    'N_i'; 'R_i';  ...
    'del_Wb'; 'del_Wp'; 'del_V'; 'r_B'; ...
    'E_m'; 't_starve'; 't_E'; 'xi_WE'; ...
    'eb_min_G'; 'eb_min_R'; ... 'ep_min'; ...
    'J_Ob'; 'J_Op'; 'J_Oi'};

  case 'hep'
    webColStat.L_e = '#DEF3BD';   
    webStatFields =  {...
    'z'; 'c_T'; ...
    's_M'; 's_Hbp'; 's_HLbp'; 's_s'; ...
    'E_0';'Wd_0'; ...
    'a_b'; 'a_p';  ...
    'Wd_b'; 'Wd_p'; 'Wd_i'; 'L_b';'L_p'; 'L_e'; ...
    'W_dWm'; 'dWm'; ...
    'N_i';  ...
    'del_Wb'; 'del_Wp'; 'del_V';  ...
    'E_m'; 't_starve'; 't_E'; 'xi_WE'; ...
    'eb_min_G'; 'eb_min_R'; ... 'ep_min'; ...
    'J_Ob'; 'J_Op'; 'J_Oi'};

  case 'hex'
     webColStat.L_e = '#DEF3BD';   
     webStatFields =  {...
    'z'; 'c_T'; ...
    's_M';  's_s'; ...
    'E_0';'Wd_0'; ...
    'a_b'; 'a_p';  ...
    'Wd_b'; 'Wd_i'; 'L_b'; 'L_e'; ...
    'W_dWm'; 'dWm'; ...
    'N_i';   ...
    'del_Wb'; 'del_V';  ...
    'E_m'; 't_starve'; 't_E'; 'xi_WE'; ...
    'eb_min_G'; 'eb_min_R'; ... 'ep_min'; ...
    'J_Ob'; 'J_Oi'};  

  otherwise
    webStatFields  = {};     
          
  end
  

% if strcmp(model,'abj')
%     webColStat.s_M = '#F7BDDE'; 
%     webColStat.a_j = webColStat.a_b;  webColStat.L_j = webColStat.L_b;  webColStat.Wd_j = webColStat.Wd_b; 
%     webColStat.J_Oj = webColStat.J_Ob;  %webColStat.p_t_j = webColStat.p_t_b; webColStat.RQ_j = webColStat.RQ_b;
% end  
  
% colours for statistics
%     '#FFC6A5'; '#FFFFFF'; '#C6E7DE'; '#CEEFBD'; '#CEEFBD';
%     '#DEF3BD'; '#FFFFC6'; '#BDC6DE'; '#C6B5DE'; '#DEBDDE';
%     '#F7BDDE'; '#C6E7DE'; '#FFFFC6'; '#FFC6A5'; '#FFFFC6'; 
%     '#F7BDDE'; '#BDC6DE'; '#FFFFC6'; '#FFFFFF'  
  
end
  
  